services:
  _defaults:
    autoconfigure: true
    autowire: true


  CodelyTv\Apps\Api\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  CodelyTv\:
    resource: '../../../src'
