services:
  _defaults:
    autoconfigure: true
    autowire: true


  RGR\Apps\Api\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  RGR\:
    resource: '../../../src'
