imports:
  - { resource: ../../../src/Crm/Shared/Infrastructure/Symfony/DependencyInjection/crm_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true


  RGR\Apps\Crm\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
    exclude: '../src/Controller/*/Request'

  RGR\:
    resource: '../../../src'

  # Wire
  RGR\Shared\:
    resource: '../../../src/Shared'

  RGR\Crm\:
    resource: '../../../src/Crm'

  # -- TAGGING --
  RGR\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
