imports:
  - { resource: ../../../src/Crm/Shared/Infrastructure/Symfony/DependencyInjection/crm_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true


  RGR\Apps\Crm\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
    exclude: '../src/Controller/*/Request'

  RGR\:
    resource: '../../../src'
